version: '3.8'

services:
  db:
    image: postgres:13
    container_name: read-me-out-db
    restart: always
    platform: linux/arm64/v8
    environment:
      POSTGRES_USER: readmeout
      POSTGRES_PASSWORD: readmeoutpass
      POSTGRES_DB: read_me_out
      # 如果需要創建多個資料庫
      # POSTGRES_MULTIPLE_DATABASES: read_me_out,read_me_out_test
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # 添加初始化腳本目錄
    ports:
      - 5432:5432

volumes:
  db-data: